FROM node:16 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install --ignore-scripts -g @nestjs/cli 

COPY prisma ./prisma/

RUN yarn install --ignore-scripts

RUN yarn gen 

COPY . .

EXPOSE 8080

CMD [ "yarn", "start:dev" ]